apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: newapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: akashmore947/sample-nodejs-project-image:3
          imagePullPolicy: Always 
          ports:
            - containerPort: 8000
